creation_rules:
  - path_regex: management-clusters/gcapv/secrets/.*\.enc\.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: 33F6B8345F76AE375342938CF8BEC7C06BF9EA8D
  - path_regex: management-clusters/gcapv/secrets/.*\.enc\.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: A25DFBBC0240AC332DA32B6DA62C831276E30730
