apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gcapv-git-repo
  namespace: default
spec:
  ignore: |-
    **
    !management-clusters/gcapv/**
    !bases/**
    **.md
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-https-credentials
  url: https://github.com/giantswarm/capv-clusters-fleet
