apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gcapeverde-gitops
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m
  path: "./management-clusters/gcapeverde"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gcapeverde-git-repo
  timeout: 2m
