apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-nginx-ingress
  namespace: org-${organization}
  labels: 
    giantswarm.io/cluster: ${cluster_name}
    giantswarm.io/managed-by: flux
spec:
  catalog: giantswarm
  name: nginx-ingress-controller-app
  namespace: kube-system
  version: 2.30.1
  kubeConfig:
    context:
      name: ${cluster_name}-kubeconfig
    inCluster: false
    secret:
      name: ${cluster_name}-kubeconfig
      namespace: org-${organization}
  userConfig:
    configMap:
      name: ${cluster_name}-nginx-ingress-controller-app-userconfig
      namespace: org-${organization}   
