apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
configMapGenerator:
  - files:
    - values=stage_config.yaml
    name: ${cluster_name}-stage-config
    namespace: org-${organization}
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
patches:
  - patch: |-
      - op: replace
        path: /spec/version
        value: 0.7.1
    target:
      kind: App
      name: \${cluster_name}-default-apps
  - patch: |-
      - op: replace
        path: /spec/version
        value: 0.17.0
    target:
      kind: App
      name: \${cluster_name}
# block end
resources:
  - ../../../clusters/openstack/template