controlPlane:
  image: ubuntu-2004-kube-v1.23.13
kubernetesVersion: v1.23.13
nodeClasses:
  default:
    bootFromVolume: true
    diskSize: 50
    flavor: n1.medium
    image: ubuntu-2004-kube-v1.23.13
  medium:
    bootFromVolume: true
    diskSize: 60
    flavor: n1.medium
    image: ubuntu-2004-kube-v1.23.13