apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/cluster: ${cluster_name}
    giantswarm.io/managed-by: flux
  name: ${cluster_name}-redis
  namespace: org-${organization}
spec:
  catalog: jfrog-helm-charts
  kubeConfig:
    context:
      name: ${cluster_name}-kubeconfig
    inCluster: false
    secret:
      name: ${cluster_name}-kubeconfig
      namespace: org-${organization}
  name: redis
  namespace: default
  version: 17.13.2