controlPlane:
  availabilityZones:
  - gb-lon-1
  - gb-lon-2
  - gb-lon-3
externalNetworkID: cdbcb519-1f91-43fb-b0a9-312f0abf8f12
nodeCIDR: 10.6.0.0/24
nodePools:
  gb-lon-1:
    class: medium
    failureDomain: gb-lon-1
    replicas: 1
  gb-lon-2:
    class: medium
    failureDomain: gb-lon-2
    replicas: 1
  gb-lon-3:
    class: medium
    failureDomain: gb-lon-3
    replicas: 1