apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
kind: Kustomization
resources:
  - appcr.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app-operator.giantswarm.io/watching: "true"
