connectivity:
  network:
    loadBalancers:
      cidrBlocks:
        - 10.10.222.132/32
controlPlane:
  machineTemplate:
    diskGiB: 50
    memoryMiB: 8096
    network:
      devices:
        - dhcp4: true
          networkName: grasshopper-capv
    numCPUs: 4
    template: ubuntu-2004-kube-v1.24.11
nodeClasses:
  default:
    diskGiB: 50
    memoryMiB: 14000
    network:
      devices:
        - dhcp4: true
          networkName: grasshopper-capv
    numCPUs: 6
    template: ubuntu-2004-kube-v1.24.11
nodePools:
  worker:
    class: default
    replicas: 2