apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
kind: Kustomization
resources:
  - cluster.yaml
configMapGenerator:
  - name: ${cluster_name}-user-values
    namespace: org-${organization}
    files:
      - values=values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app-operator.giantswarm.io/watching: "true"
